def seed_books

  books = [{title: "A Brief History of Seven Killings",
            description: "Marlon James’ 2015 Man Booker Prize- and American Book Award-winning novel is a dazzling, vivid dive into 1970s Kingston, Jamaica. It’s an epic of the highest order, the plot of which hinges on the 1976 assassination attempt on the life of Bob Marley.",
            author: "Marlon James",
            category: "Thriller",
            publisher: "Publisher A",
            unit_price: 17.0,
            published_date: "2017-01-01",
            book_image: File.open("#{Rails.root}/public/books_images/a_brief_history.jpeg")
          },
          { title: "A Heartbreaking Work of Staggering Genius",
            description: "Dave Eggers’ daring and exuberant 2000 memoir chronicles his guardianship over his younger brother Christopher (“Toph”) after losing their parents to cancer.",
            author: "Dave Eggers",
            category: "Drama",
            publisher: "Publisher A",
            unit_price: 15.95,
            published_date: "2017-01-07",
            book_image: File.open("#{Rails.root}/public/books_images/a_heartbreaking_work.jpeg")
          },
          { title: "A Lesson Before Dying",
            description: "Ernest J. Gaines’ essential 1993 novel is set in fictional Bayonne, Louisiana, where Grant Wiggins, a teacher, is compelled to visit a wrongfully imprisoned man named Jefferson who has been sentenced to death; the two men build a relationship in the shadow of Jefferson’s impending execution.",
            author: "Ernest J. Gaines",
            category: "Crime",
            publisher: "Publisher B",
            unit_price: 14.0,
            published_date: "1993-08-05",
            book_image: File.open("#{Rails.root}/public/books_images/a_lesson_before_dying.jpeg")
          },
          { title: "A Little Life",
            description: "A finalist for both the Man Booker Prize and National Book Award, Hanya Yanagihara’s A Little Life explores the lives of four friends whose lives diverge and splinter in the years after they leave college.",
            author: "Hanya Yanagihara",
            category: "Action and Adventure",
            publisher: "Publisher C",
            unit_price: 17.0,
            published_date: "1988-09-13",
            book_image: File.open("#{Rails.root}/public/books_images/a_little_life.jpeg")
          },
          { title: "A Spool of Blue Thread",
            description: "This novel explores four generations of the Whitshank family, the threads their lives follow over the decades, and the family home that plays host to it all.",
            author: "Anne Tyler",
            category: "Drama",
            publisher: "Publisher A",
            unit_price: 16.0,
            published_date: "2017-01-01",
            book_image: File.open("#{Rails.root}/public/books_images/a_spool_of_blue_thread.jpeg")
          },
          { title: "A Thousand Acres",
            description: "Jane Smiley’s Pulitzer Prize-winning novel is a contemporary reimagining of Shakespeare’s King Lear. In it, an Iowa farmer seeks to divide his farm between his three daughters, the youngest of which opposes his plans.",
            author: "Jane Smiley",
            category: "Drama",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "1998-09-21",
            book_image: File.open("#{Rails.root}/public/books_images/a_thousand_acres.jpeg")
          },
          { title: "A Visit from the Goon Squad",
            description: "This stunning Pulitzer honoree excavates the inner lives of characters whose paths weave in and out, colliding with each other against the background of the music industry.",
            author: "Jennifer Egan",
            category: "Action and Adventure",
            publisher: "Publisher B",
            unit_price: 16.0,
            published_date: "1985-06-03",
            book_image: File.open("#{Rails.root}/public/books_images/a_visit_from_goon_squad.jpeg")
          },
          { title: "All the Light We Cannot See",
            description: "Anthony Doerr’s lauded 2014 novel immerses readers in World War II-era France during the occupation. The paths of a blind French girl and a young German boy intersect amid the dangers of war.",
            author: "Anthony Doerr",
            category: "History",
            publisher: "Publisher A",
            unit_price: 27.0,
            published_date: "2014-08-07",
            book_image: File.open("#{Rails.root}/public/books_images/all_the_light.jpeg")
          },
          { title: "American Pastoral",
            description: "The first installment in Philip Roth’s American Trilogy charts the course of fortune, privilege, and disaster as one family’s placid existence is upended by the very community that first provided it.",
            author: "Philip Roth",
            category: "Crime",
            publisher: "Publisher D",
            unit_price: 16.95,
            published_date: "2012-01-09",
            book_image: File.open("#{Rails.root}/public/books_images/american_pastoral.jpeg")
          },
          { title: "Americanah",
            description: "In this story, Ifemelu and Obinze leave their home in Nigeria to build lives in America and London. After years apart, they reunite once more in Nigeria, finding both themselves and their home utterly changed.",
            author: "Chimamanda Ngozi Adichie",
            category: "Romance",
            publisher: "Publisher D",
            unit_price: 16.95,
            published_date: "2000-05-22",
            book_image: File.open("#{Rails.root}/public/books_images/americanah.jpeg")
          },
          { title: "Amsterdam",
            description: "This Booker Prize-winning novel introduces readers to two friends, Clive Linely and Vernon Halliday, whose lives are connected by a woman named Molly Lane—whom both men once loved.",
            author: "Ian McEwan",
            category: "Romance",
            publisher: "Publisher B",
            unit_price: 14.95,
            published_date: "2002-01-25",
            book_image: File.open("#{Rails.root}/public/books_images/amsterdam.jpeg")
          },
          { title: "Angle of Repose",
            description: "The American West comes to glimmering life in this book, which follows a retired professor named Lyman Ward as he returns to Grass Valley, California, to compile a biography of his dynamic grandmother.",
            author: "Wallace Stegner",
            category: "Family",
            publisher: "Publisher A",
            unit_price: 16.95,
            published_date: "1999-10-12",
            book_image: File.open("#{Rails.root}/public/books_images/angle_of_repose.jpeg")
          },
          { title: "Beloved",
            description: "Toni Morrison won the Pulitzer Prize and the American Book Award for her unforgettable novel Beloved, which illuminates the life of Sethe, a former slave whose life is haunted by the horrors she endured years earlier. Morrison was also awarded the Nobel Prize in Literature in 1993.",
            author: "Toni Morrison",
            category: "Drama",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "1992-07-23",
            book_image: File.open("#{Rails.root}/public/books_images/beloved.jpeg")
          },
          { title: "Birds of America",
            description: "These twelve stories crackle with truth, spanning the globe and excavating the quibbles, wits, and humors of memorable characters and situations, as is writer Lorrie Moore’s specialty.",
            author: "Lorrie Moore",
            category: "Humor",
            publisher: "Publisher D",
            unit_price: 15.95,
            published_date: "2011-10-12",
            book_image: File.open("#{Rails.root}/public/books_images/birds_of_america.jpeg")
          },
          { title: "Cold Mountain",
            description: "This love story set during the American Civil War became an instant classic when it was published in 1997. It tells the intertwined stories of Ada and Inman, two people separated by war and trying to make their ways back to each other.",
            author: "Charles Frazier",
            category: "Romance",
            publisher: "Publisher B",
            unit_price: 16.0,
            published_date: "2006-07-12",
            book_image: File.open("#{Rails.root}/public/books_images/cold_mountain.jpeg")
          },
          { title: "Dear Life: Stories",
            description: "Nobel Prize-winning writer Alice Munro has written countless short story collections, each one more exciting, more spellbinding than the last",
            author: "Alice Munro",
            category: "Story Collection",
            publisher: "Publisher A",
            unit_price: 15.95,
            published_date: "2012-02-15",
            book_image: File.open("#{Rails.root}/public/books_images/dear_life_stories.jpeg")
          },
          { title: "Gilead",
            description: "This quietly stunning epistolary novel grapples with family relationships—especially those between fathers and sons—as Reverend John Ames records his memories on paper for his young son.",
            author: "Marilynne Robinson",
            category: "Family",
            publisher: "Publisher D",
            unit_price: 16.0,
            published_date: "1999-07-12",
            book_image: File.open("#{Rails.root}/public/books_images/gilead.jpeg")
          },
          { title: "I Know Why the Caged Bird Sings",
            description: "Oprah Winfrey says it best in the forward to this moving memoir: “Maya Angelou lived what she wrote. She understood that sharing her truth connected her to the greater human truths—of longing, abandonment, security, hope, winder, prejudice, mystery, and, finally, self-discovery: the realization of who you really are and the liberation that love brings. And each of those timeless truths unfolds in this first autobiographical account of her life.",
            author: "Maya Angelou",
            category: "Autobiography",
            publisher: "Publisher C",
            unit_price: 7.99,
            published_date: "1995-03-17",
            book_image: File.open("#{Rails.root}/public/books_images/i_know_why.jpeg")
          },
          { title: "Infinite Jest",
            description: "This novel isn’t just notable for its length (it clocks in at a whopping 1079 pages); it’s also a rollicking comedy unafraid of delving into the difficult questions that consume and confound humanity.",
            author: "David Foster Wallace",
            category: "Humor",
            publisher: "Publisher D",
            unit_price: 20.0,
            published_date: "1979-09-22",
            book_image: File.open("#{Rails.root}/public/books_images/infinite_jest.jpeg")
          },
          { title: "Interpreter of Maladies",
            description: "The characters in Jhumpa Lahiri’s Pulitzer Prize-winning collection grapple with change, reimagine their inheritances and their ailments, and struggle to navigate new worlds both physical and cultural.",
            author: "Jhumpa Lahiri",
            category: "Religion, Spirituality & New Age",
            publisher: "Publisher A",
            unit_price: 14.95,
            published_date: "1994-02-12",
            book_image: File.open("#{Rails.root}/public/books_images/interpreter_of_maladies.jpeg")
          },
          { title: "Let the Great World Spin",
            description: "1970s New York plays host to this compelling novel by Colum McCann, the landscape of the city laid vividly bare alongside the interwoven lives of his characters.",
            author: "Colum McCann",
            category: "Drama",
            publisher: "Publisher C",
            unit_price: 17.0,
            published_date: "1985-07-13",
            book_image: File.open("#{Rails.root}/public/books_images/let_the_great_world_spin.jpeg")
          },
          { title: "Love in the Time of Cholera",
            description: "Two youths in love, Florentino Arizia and Fermina Daza, find each other again after 50 years in this dazzling novel by Gabriel Garcia Marquez.",
            author: "Gabriel Garcia Marquez",
            category: "Romance",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "1982-09-20",
            book_image: File.open("#{Rails.root}/public/books_images/love_in_the_time_of_cholera.jpeg")
          },
          { title: "March",
            description: "Geraldine Brooks reimagines the world of Little Women by giving voice to the absent patriarch of the March family and unearthing the upheavals that war can inflict on families and the fathers that love them.",
            author: "Geraldine Brooks",
            category: "Family",
            publisher: "Publisher D",
            unit_price: 16.0,
            published_date: "1989-05-19",
            book_image: File.open("#{Rails.root}/public/books_images/march.jpeg")
          },
          { title: "Middlesex",
            description: "Jeffrey Eugenides’ 2002 Pulitzer Prize-winning novel is the coming-of-age story of Cal Stephanides, an intersex man coming to understand his gender identity. The novel traces the effect of a mutated gene throughout generations of Cal’s Greek family, examining social constructs of gender as well as the immigrant experience in America.",
            author: "Jeffrey Eugenides",
            category: "Science",
            publisher: "Publisher A",
            unit_price: 18.0,
            published_date: "2002-01-15",
            book_image: File.open("#{Rails.root}/public/books_images/middlesex.jpeg")
          },
          { title: "Midnight’s Children",
            description: "Saleem Sinai, The central character in Salman Rushdie’s Midnight’s Children, is born at midnight on August 15, 1947, the moment at which India becomes independent. This coincidence has consequences, however, as his fate is bound up with that of his country—and the other midnight’s children with whom he is connected.",
            author: "Salman Rushdie",
            category: "Drama",
            publisher: "Publisher D",
            unit_price: 18.0,
            published_date: "1999-09-12",
            book_image: File.open("#{Rails.root}/public/books_images/midnights_children.jpeg")
          },
          { title: "My Struggle, Book 1",
            description: "Karl Ove Knausgaard’s six-volume autobiography engages with enormous themes even as it delves into the smallest, most intimate details of daily human life. You’ll devour it.",
            author: "Karl Ove Knausgaard",
            category: "Autobiography",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "2003-02-15",
            book_image: File.open("#{Rails.root}/public/books_images/my_struggle_book_1.jpeg")
          },
          { title: "Salvage the Bones",
            description: "Uncontrollable natural forces mirror the tumult and sacrifice of family life in this astonishing novel by Jesmyn Ward. Set in the days before the arrival and accompanying destruction of Hurricane Katrina, the story introduces Esch and her three brothers, Skeetah, Randall, and Junior, who navigate life in their small town and make preparations for the imminent storm.",
            author: "Jesmyn Ward",
            category: "Family",
            publisher: "Publisher B",
            unit_price: 17.0,
            published_date: "2016-09-20",
            book_image: File.open("#{Rails.root}/public/books_images/salvage_the_bones.jpeg")
          },
          { title: "Shadow Country",
            description: "Set in the Florida Everglades at the turn of the century, Peter Matthiessen’s 2008 National Book Award-winning novel submerges readers in a wild and mysterious story about the outlaw sugar planter E. J. Watson.",
            author: "Peter Matthiessen",
            category: "Drama",
            publisher: "Publisher C",
            unit_price: 20.0,
            published_date: "2008-05-13",
            book_image: File.open("#{Rails.root}/public/books_images/shadow_country.jpeg")
          },
          { title: "Tenth of December: Stories",
            description: "In her New York Times review, Michiko Kakutani described this short story collection as “A visceral and moving act of storytelling […] No one writes more powerfully than George Saunders about the lost, the unlucky, the disenfranchised.” Devour Saunders’ short stories (and his first novel, Lincoln in the Bardo), and return to them again and again.",
            author: "George Saunders",
            category: "Story Collection",
            publisher: "Publisher A",
            unit_price: 16.0,
            published_date: "2013-02-02",
            book_image: File.open("#{Rails.root}/public/books_images/tenth_of_december.jpeg")
          },
          { title: "The Brief Wondrous Life of Oscar Wao",
            description: "The comedy and tragedy of Junot Diaz’s much-lauded novel rests with Oscar, Diaz’s hero, who struggles, perseveres, and sacrifices everything in his lifelong search for love.",
            author: "Junot Diaz",
            category: "Romance",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "2012-01-01",
            book_image: File.open("#{Rails.root}/public/books_images/the_brief_wondrous_life.jpeg")
          },
          { title: "The Color Purple",
            description: "Grief and rebirth fuel this heart-rending Pulitzer- and National Book Award-winning novel by Alice Walker, which tells the story of Celie, her life in rural Georgia, her tragedies, and her triumphs through her letters and diary entries.",
            author: "Alice Walker",
            category: "Drama",
            publisher: "Publisher D",
            unit_price: 14.95,
            published_date: "1989-01-02",
            book_image: File.open("#{Rails.root}/public/books_images/the_color_purple.jpeg")
          },
          { title: "The God of Small Things",
            description: "Arundhati Roy’s prose spins webs of magic, stunning readers and stealing breath through gorgeously crafted sentences. Roy’s debut novel tells the story of a family in India whose lives are haunted and forever altered by one tragic event and its accompanying mysteries big and small.",
            author: "Arundhati Roy",
            category: "Family",
            publisher: "Publisher B",
            unit_price: 17.0,
            published_date: "2001-04-12",
            book_image: File.open("#{Rails.root}/public/books_images/the_god_of_small_things.jpeg")
          },
          { title: "The Goldfinch",
            description: "Donna Tartt’s novel of grief, art, and adventure won the Pulitzer Prize in 2014. It tells the story of Theo, a 13-year-old boy whose life takes an unexpected turn when tragedy strikes his family in New York.",
            author: "Donna Tartt",
            category: "Family",
            publisher: "Publisher B",
            unit_price: 20.0,
            published_date: "2013-04-23",
            book_image: File.open("#{Rails.root}/public/books_images/the_goldfinch.jpeg")
          },
          { title: "The Good Lord Bird",
            description: "This rollicking and irreverent novel by author James McBride follows famed abolitionist John Brown and Henry, the young freed slave who narrates the novel and joins Brown on their peripatetic adventures across the country (disguised as a young girl all the while). McBride’s novel won the National Book Award in 2013.",
            author: "James McBride",
            category: "Action and Adventure",
            publisher: "Publisher D",
            unit_price: 16.0,
            published_date: "2012-07-12",
            book_image: File.open("#{Rails.root}/public/books_images/the_good_lord_bird.jpeg")
          },
          { title: "The Hours",
            description: "In The Hours, Michael Cunningham interweaves three stories—two fictional, one based in fact. Virginia Woolf, a poet named Samuel, and his friend Clarissa come into focus, each suspended with their own challenges within their own decades, the reach of which span nearly a century.",
            author: "Michael Cunningham",
            category: "Story Colletio ",
            publisher: "Publisher D",
            unit_price: 16.0,
            published_date: "2011-01-10",
            book_image: File.open("#{Rails.root}/public/books_images/the_hours.jpeg")
          },
          { title: "The House on Mango Street",
            description: "Sandra Cisneros’ beloved book tells the story of Esperanza Cordero, a young girl coming of age in Chicago and deciding who she wants to be in the house on Mango Street and in the ever-changing world beyond.",
            author: "Sandra Cisneros",
            category: "Action and Adventure",
            publisher: "Publisher C",
            unit_price: 11.95,
            published_date: "2011-12-12",
            book_image: File.open("#{Rails.root}/public/books_images/the_house_on_mango_street.jpeg")
          },
          { title: "The Joy Luck Club",
            description: "In her beautifully crafted novel The Joy Luck Club, Amy Tan tells the stories of four mothers and four daughters whose lives are entangled with one another's, beginning with the shared supper tradition the mothers call the Joy Luck Club. Their lives, secrets, and relationships unspool over decades.",
            author: "Amy Tan",
            category: "Family",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "2001-07-12",
            book_image: File.open("#{Rails.root}/public/books_images/the_joy_luck_club.jpeg")
          },
          { title: "The Luminaries",
            description: "This astonishing Man Booker Prize-winning novel is set in New Zealand in 1866—in the middle of the country’s gold rush—where author Eleanor Catton builds a story at once suspenseful, luminous, and utterly unexpected.",
            author: "Eleanor Catton",
            category: "Thriller",
            publisher: "Publisher B",
            unit_price: 15.0,
            published_date: "1987-01-18",
            book_image: File.open("#{Rails.root}/public/books_images/the_luminaries.jpeg")
          },
          { title: "The Remains of the Day",
            description: "Amid the changes roaring through post World War II-England, a butler named Stevens grapples with broken expectations and the country’s altered social landscape, and, for the first time, he begins to question his role within it all.",
            author: "Kazuo Ishiguro",
            category: "Drama",
            publisher: "Publisher C",
            unit_price: 16.0,
            published_date: "1988-11-16",
            book_image: File.open("#{Rails.root}/public/books_images/the_remains_of_the_day.jpeg")
          },
          { title: "The Road",
            description: "Cormac McCarthy’s post-apocalyptic vision of America follows a father and son as they journey through a scorched country, scavenging amid the destruction and defending themselves against the dangers they find there.",
            author: "Cormac McCarthy",
            category: "Thriller",
            publisher: "Publisher A",
            unit_price: 16.99,
            published_date: "2010-04-16",
            book_image: File.open("#{Rails.root}/public/books_images/the_road.jpeg")
          },
          { title: "The Round House",
            description: "This National Book Award winner is set in North Dakota on the Ojibwe reservation, where a boy comes of age amid tectonic shifts in his family—shifts that are spurred by a mystery, a crime that shakes the place to its core.",
            author: "Louise Erdrich",
            category: "Crime",
            publisher: "Publisher D",
            unit_price: 15.99,
            published_date: "1992-05-15",
            book_image: File.open("#{Rails.root}/public/books_images/the_round_house.jpeg")
          },
          { title: "The Sellout",
            description: "Paul Beatty’s Man Booker Prize-winning novel is a sharp satire about race, equality, urban life, and family that is set outside Los Angeles and filled with Beatty’s addictively comic voice.",
            author: "Paul Beatty",
            category: "Humor",
            publisher: "Publisher B",
            unit_price: 16.0,
            published_date: "2011-04-25",
            book_image: File.open("#{Rails.root}/public/books_images/the_sellout.jpeg")
          },
          { title: "The Shipping News",
            description: "The Shipping News spins a tale of a crumbling family in Newfoundland, relatives thrown together in a bleak home on a stark landscape who struggle to come to terms with the lives they’ve begun to live.",
            author: "Annie Proulx",
            category: "Family",
            publisher: "Publisher A",
            unit_price: 16.0,
            published_date: "2007-08-14",
            book_image: File.open("#{Rails.root}/public/books_images/the_shipping_news.jpeg")
          },
          { title: "The Signature of All Things",
            description: "In this beautifully crafted novel, Elizabeth Gilbert weaves a glimmering biography of one Alma Whittaker, a woman born with the century who comes of age in 1800s America, becomes a gifted botanist, and searches for fulfillment, enlightenment, and atonement in the natural world and across the globe.",
            author: "Elizabeth Gilbert",
            category: "Science",
            publisher: "Publisher C",
            unit_price: 17.0,
            published_date: "1979-03-17",
            book_image: File.open("#{Rails.root}/public/books_images/the_signature_of_all_things.jpeg")
          },
          { title: "The Stone Diaries",
            description: "This fictional autobiography tells the life story of Daisy Goodwill Flett, a woman whose ordinary days belie the dynamic interior world she cultivates and shares on paper in this Pulitzer Prize-winning book.",
            author: "Carol Shields",
            category: "Autobiography",
            publisher: "Publisher C",
            unit_price: 17.0,
            published_date: "2012-09-01",
            book_image: File.open("#{Rails.root}/public/books_images/the_stone_diaries.jpeg")
          },
          { title: "The Sympathizer",
            description: "Viet Thanh Nguyen’s Pulitzer Prize-winning debut novel about a half-French, half-Vietnamese communist double agent promises pulse-pounding thrills, espionage-driven twists, and a dose of compelling, clear-eyed humor.",
            author: "Viet Thanh Nguyen",
            category: "Humor",
            publisher: "Publisher D",
            unit_price: 16.0,
            published_date: "1997-04-10",
            book_image: File.open("#{Rails.root}/public/books_images/the_sympathizer.jpeg")
          },
          { title: "The Underground Railroad",
            description: "Colson Whitehead combines fantasy and brutal reality in this astonishing National Book Award-winning novel about Cora, a slave on a Georgia cotton plantation who escapes bondage via the Underground Railroad, which, in Whitehead’s imagination, comes to life as an actual network below ground. In this odyssey, Cora navigates dangers that span centuries with only her indomitable will to guide her.",
            author: "Colson Whitehead",
            category: "Thriller",
            publisher: "Publisher B",
            unit_price: 26.95,
            published_date: "2012-05-21",
            book_image: File.open("#{Rails.root}/public/books_images/the_underground_railroad.jpeg")
          },
          { title: "White Noise",
            description: "The white noise of modern life gets a physical representation in this National Book Award-winning novel when an “airborne toxic event” is unleashed and begins to loom over the lives of college professor Jack Gladney and his family.",
            author: "Don DeLillo",
            category: "Family",
            publisher: "Publisher D",
            unit_price: 17.0,
            published_date: "2011-01-18",
            book_image: File.open("#{Rails.root}/public/books_images/white_noise.jpeg")
          },
          { title: "White Teeth",
            description: "Zadie Smith’s 2000 debut remains a must-read. It explores the lives of Archie Jones and Samad Iqbal, World War II veterans whose lives burgeon and entangle across the decades and amid the rapidly changing landscape of 20th-century London.",
            author: "Zadie Smith",
            category: "Thriller",
            publisher: "Publisher A",
            unit_price: 16.95,
            published_date: "2000-05-11",
            book_image: File.open("#{Rails.root}/public/books_images/white_teeth.jpeg")
          },
          { title: "Wolf Hall",
            description: "Hilary Mantel’s brilliant, Booker Prize-winning novel reimagines the lives of Henry VIII and Thomas Cromwell, two men who upended tradition to remake England in the 1520s.",
            author: "Hilary Mantel",
            category: "History",
            publisher: "Publisher A",
            unit_price: 17.0,
            published_date: "1979-09-12",
            book_image: File.open("#{Rails.root}/public/books_images/wolf_hall.jpeg")
          }
        ]
  books.each do |b|
    b[:author] = Author.find_or_create_by(name: b[:author])
    b[:category] = Category.find_or_create_by(name: b[:category])
    b[:publisher] = Publisher.find_or_create_by(name: b[:publisher])

    Book.create(b) unless Book.find_by(title: b[:title]).present?
  end
end

def search_book(search_param)
  Book.search(search_param)
end

